'use client';

import { ROLES, DIFFICULTIES, TOPICS, SESSION_LENGTHS, CORE_TOPIC_GROUPS } from '@/lib/constants';
import { Role, SessionConfig } from '@/types';
import { useIsMobile } from '@/hooks/useIsMobile';

interface HomeScreenProps {
  config: SessionConfig;
  onConfigChange: (c: SessionConfig) => void;
  onStart: () => void;
}

export default function HomeScreen({ config, onConfigChange, onStart }: HomeScreenProps) {
  const isMobile = useIsMobile();
  const set = (partial: Partial<SessionConfig>) => onConfigChange({ ...config, ...partial });

  const toggleTopic = (id: string) => {
    const has = config.topics.includes(id);
    set({ topics: has ? config.topics.filter(t => t !== id) : [...config.topics, id] });
  };

  const isGroupActive = (subtopics: string[]) => subtopics.some(s => config.topics.includes(s));

  const toggleGroup = (subtopics: string[]) => {
    const allActive = subtopics.every(s => config.topics.includes(s));
    set({ topics: allActive ? config.topics.filter(t => !subtopics.includes(t)) : Array.from(new Set([...config.topics, ...subtopics])) });
  };

  return (
    <div style={{ maxWidth: 680 }}>

      {/* Header */}
      <div style={{ marginBottom: isMobile ? 28 : 40 }}>
        <div style={{ fontSize: 12, fontWeight: 500, color: 'var(--accent)', letterSpacing: '.06em', textTransform: 'uppercase', marginBottom: 10 }}>
          IT Interview Practice
        </div>
        <h1 style={{ fontSize: isMobile ? 24 : 32, fontWeight: 700, color: 'var(--text)', lineHeight: 1.2, marginBottom: 8 }}>
          Ready to practice?
        </h1>
        <p style={{ fontSize: 14, color: 'var(--muted)', lineHeight: 1.6 }}>
          Configure your session below. Questions are generated by AI — short, direct, and based on real interviews.
        </p>
      </div>

      {/* Role */}
      <Section label="Your Role">
        {/* CSS class handles 3→2 col responsive breakpoint */}
        <div className="role-grid">
          {ROLES.map(r => (
            <RoleCard key={r.id} role={r} selected={config.role.id === r.id} onClick={() => set({ role: r })} />
          ))}
        </div>
      </Section>

      {/* Difficulty */}
      <Section label="Experience Level">
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
          {DIFFICULTIES.map(d => (
            <Chip key={d} active={config.difficulty === d} onClick={() => set({ difficulty: d })}>{d}</Chip>
          ))}
        </div>
      </Section>

      {/* Topic groups */}
      <Section label="Focus Areas" hint="optional — leave blank to use role defaults">
        <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginBottom: 12 }}>
          {CORE_TOPIC_GROUPS.map(g => (
            <button
              key={g.id}
              onClick={() => toggleGroup(g.subtopics)}
              style={{
                padding: '5px 12px', borderRadius: 20, fontSize: 12, cursor: 'pointer',
                border: `1px solid ${isGroupActive(g.subtopics) ? 'var(--accent)' : 'var(--border)'}`,
                background: isGroupActive(g.subtopics) ? 'var(--accentbg)' : 'transparent',
                color: isGroupActive(g.subtopics) ? 'var(--accent)' : 'var(--muted)',
                fontFamily: 'Inter, sans-serif', fontWeight: 500, transition: '.15s',
                display: 'flex', alignItems: 'center', gap: 5,
              }}
            >
              {g.icon} {g.label}
            </button>
          ))}
        </div>
        {/* CSS class handles responsive columns */}
        <div className="topic-grid">
          {TOPICS.map(t => {
            const on = config.topics.includes(t.id);
            return (
              <button
                key={t.id}
                onClick={() => toggleTopic(t.id)}
                style={{
                  padding: '10px 12px', borderRadius: 8, cursor: 'pointer', textAlign: 'left',
                  border: `1px solid ${on ? 'var(--accent)' : 'var(--border)'}`,
                  background: on ? 'var(--accentbg)' : 'var(--card)',
                  transition: '.15s', fontFamily: 'Inter, sans-serif',
                }}
              >
                <div style={{ fontSize: 15, marginBottom: 3 }}>{t.icon}</div>
                <div style={{ fontSize: 12, fontWeight: 500, color: on ? 'var(--accent)' : 'var(--text)', marginBottom: 2 }}>{t.label}</div>
                <div style={{ fontSize: 10, color: 'var(--muted)', lineHeight: 1.4 }}>{t.description}</div>
              </button>
            );
          })}
        </div>

        {config.topics.length > 0 && (
          <div style={{
            marginTop: 10, padding: '8px 12px', borderRadius: 8, fontSize: 12,
            background: 'var(--accentbg)', border: '1px solid var(--accent)', color: 'var(--accent)',
          }}>
            Focusing on: {config.topics.map(id => TOPICS.find(t => t.id === id)?.label).filter(Boolean).join(' · ')}
          </div>
        )}
      </Section>

      {/* Length */}
      <Section label="Session Length">
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
          {SESSION_LENGTHS.map(l => (
            <Chip key={l.value} active={config.length === l.value} onClick={() => set({ length: l.value })}>{l.label}</Chip>
          ))}
        </div>
      </Section>

      {/* Start */}
      <button
        onClick={onStart}
        style={{
          marginTop: 8,
          padding: isMobile ? '13px 0' : '12px 28px',
          width: isMobile ? '100%' : 'auto',
          borderRadius: 10, border: 'none',
          background: 'linear-gradient(135deg, var(--accent), var(--accent2))',
          color: '#fff', fontSize: 14, fontWeight: 600, cursor: 'pointer',
          fontFamily: 'Inter, sans-serif', letterSpacing: '.01em',
          display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 8,
          boxShadow: '0 2px 12px rgba(108,142,245,0.35)',
          transition: 'opacity .15s, transform .15s',
        }}
        onMouseEnter={e => { (e.currentTarget as HTMLElement).style.opacity = '.88'; (e.currentTarget as HTMLElement).style.transform = 'translateY(-1px)'; }}
        onMouseLeave={e => { (e.currentTarget as HTMLElement).style.opacity = '1'; (e.currentTarget as HTMLElement).style.transform = 'translateY(0)'; }}
      >
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
          <polygon points="5 3 19 12 5 21 5 3" />
        </svg>
        Start Interview
      </button>
    </div>
  );
}

function Section({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 28 }}>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 8, marginBottom: 12, flexWrap: 'wrap' }}>
        <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--text)', textTransform: 'uppercase', letterSpacing: '.06em' }}>{label}</div>
        {hint && <div style={{ fontSize: 11, color: 'var(--muted)' }}>{hint}</div>}
      </div>
      {children}
    </div>
  );
}

function RoleCard({ role, selected, onClick }: { role: Role; selected: boolean; onClick: () => void }) {
  return (
    <button
      onClick={onClick}
      style={{
        background: selected ? 'var(--accentbg)' : 'var(--card)',
        border: `1px solid ${selected ? 'var(--accent)' : 'var(--border)'}`,
        borderRadius: 10, padding: '14px 12px', cursor: 'pointer',
        textAlign: 'left', transition: '.15s', width: '100%', fontFamily: 'Inter, sans-serif',
        position: 'relative', overflow: 'hidden',
      }}
    >
      {selected && (
        <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 2, background: 'linear-gradient(90deg, var(--accent), var(--accent2))' }} />
      )}
      <div style={{ fontSize: 20, marginBottom: 6 }}>{role.icon}</div>
      <div style={{ fontSize: 12, fontWeight: 600, color: selected ? 'var(--accent)' : 'var(--text)', marginBottom: 3 }}>{role.name}</div>
      <div style={{ fontSize: 10, color: 'var(--muted)' }}>{role.topics.slice(0, 2).join(' · ')}</div>
    </button>
  );
}

function Chip({ children, active, onClick }: { children: React.ReactNode; active: boolean; onClick: () => void }) {
  return (
    <button
      onClick={onClick}
      style={{
        padding: '7px 16px', borderRadius: 20, fontSize: 12, fontWeight: 500,
        border: `1px solid ${active ? 'var(--accent)' : 'var(--border)'}`,
        background: active ? 'var(--accent)' : 'transparent',
        color: active ? '#fff' : 'var(--text2)',
        cursor: 'pointer', fontFamily: 'Inter, sans-serif', transition: '.15s',
      }}
    >
      {children}
    </button>
  );
}